/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    categories: Category;
    posts: Post;
    users: User;
  };
  globals: {
    menu: Menu;
  };
}
export interface Category {
  id: string;
  title?: string;
  subcategories?: string[] | Category[];
  updatedAt: string;
  createdAt: string;
}
export interface Post {
  id: string;
  text?: string;
  category?: string | Category;
  parentCategory?: string | Category;
  updatedAt: string;
  createdAt: string;
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Menu {
  id: string;
  globalText?: string;
  updatedAt?: string;
  createdAt?: string;
}
